spring:
  datasource:
      url: jdbc:mysql://localhost:3307/cartTest?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
flyway:
  locations: classpath:/db.migration
  url: jdbc:mysql://mysql:3307/cartTest?useUnicode=yes&characterEncoding=UTF-8
  user: root
  password: root