version: '2'
services:
  db:
    image: mysql:5.7
    container_name: cart
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=cart
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - cart
networks:
  main: