version: '2'
services:
  db:
    image: mysql:5.7
    container_name: cart
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=cart
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - cart

  mysql:
    image: mysql:5.7
    container_name: cartTest
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=cartTest
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - cartTest
networks:
  main: